# EPS400/522
#### Computational Methods for Geoscience - Fall 2023
#### Instructor: Eric Lindsey
---------

# Assignments for Lab 1

This notebook contains some assignments (or puzzles) you should try to solve to improve your understanding of python and make sure you understood the things you read in the examples notebook. Some of them are harder than others, don't feel bad if the solution seems unreachable or confusing! This is all part of the learning process. If you are stuck, feel free to ask your neighbor, the instructors, google, or even a Chat AI for help. 

It's OK if you don't get through everything. The last assignments especially are designed to challenge you, and if they feel overwhelming now, try coming back to them in a couple days - you may be surprised how much you've learned!

This assignment will not be graded and you don't need to turn it in (unless you want to)!

### 0. Bug Assignment:

In [1]:
#This cell has two bugs. First run it to see the error message, then try to fix the bugs one at a time.

print("I have fixed the bugs!")

I have fixed the bugs!


### 1. Variables assignment: radians/degrees
Create a variable called "deg2rad" that will convert degrees into radians whenever you multiply it by a value in degrees. For example, we want this to work correctly for any value `number_in_degrees`:

    number_in_radians = number_in_degrees * deg2rad

Test your work by demonstrating that 180 degrees is equal to pi radians.

Then compute 1 degree in radians, and 1 radian in degrees.

Hint: radians = degrees * pi / 180 

Second hint: to use a more exact value of "pi", you have to import numpy as np. Then you can use "np.pi"


In [13]:
# put your work here.

import numpy as np

def deg2rad(degrees):
    radians=np.pi * degrees / 180
    return radians

def rad2deg(radians):
    degrees = 180/np.pi * radians
    return degrees

print(f'180 degrees is {deg2rad(180)} radians')
print(f'{np.pi} radians is {rad2deg(np.pi)} degrees')


180 degrees is 3.141592653589793 radians
3.141592653589793 radians is 180.0 degrees


### 2. Numbers assignment
Write a function that will calculate the time that a signal takes to reach us from a GPS satellite, given the speed of light is roughly 2.99 x 10^8 meters/second. The altitude of the GPS satellite above the surface of Earth is 20,000 kilometers. 

You have the following tasks:

(a) Define a variable for the speed of light, using scientific notation. In python this is done with 'e'. For example, `4.34e5` is equal to 434,000


In [ ]:
light_speed=2.99e8

(b) Define a variable for the altitude of the GPS satellite, in meters, also using scientific notation (be careful of units here!)

 

In [ ]:
altitude = 20000 * 1000

 (c) Use the formula Time = Distance/Velocity, to calculate the time required by the signal to reach the Earth from the GPS satellite Assign the result to a new variable and print out the result.



In [17]:
light_speed=2.99e8
altitude = 20000 * 1000

travel_time = altitude / light_speed
print(f'Travel time is {travel_time} seconds')

Travel time is 0.06688963210702341 seconds


### 3. String assignment: 
Using the altitude and travel-time variables you calculated in part 2 above, print out the time traveled by the signal as a nicely formatted sentence:

    The time taken by the signal from a GPS satellite at an altitude of XXXX km to reach the Earth is X.XXXXX seconds.

  TIP: to print a variable using print() use the following syntax, where %f is the place-holder for a floating point variable, given with %variable at the end of the line:


      print ('the variable value is %f' %value) 
      
You can use other formatting options: %s for strings, and %d for integers. If you want to include more than one variable, you can list them in parentheses:


      print ('the first value is %f, the second is %d' %(value1,value2)) 
      
Finally, for floating point values you can control the number of values after the decimal point with e.g. "%.2f" for 2 decimal values.

Note, this is only one way of generating nicely formatted strings. Check out this page for (much) more information if you are interested: https://realpython.com/python-string-formatting/

In [28]:
light_speed=2.99e8
altitude = 20000 * 1000

travel_time = altitude / light_speed

print('The time taken by the signal from a GPS satellite at an altitude of %d km to reach the Earth is %.2f seconds' %(altitude/1000, travel_time))

The time taken by the signal from a GPS satellite at an altitude of 20000 km to reach the Earth is 0.07 seconds


### 4. Expression assignment
Define a variable, then create an expression that determines whether one computation done with that variable is larger than or smaller than another one. Your expression should return either "True" or "False" and save that value to a new variable. Then print out both the value and the type of that variable.

In [33]:
var1 = 3

if (var1*3) > (var1^3):
    greater=True
else:
    greater=False

print(f'{greater}, {type(greater)}')

True, <class 'bool'>


### 5. List assignment: 

a. Add 'kiwi' to the following list, before 'cherry', and print out the result

In [35]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "kiwi")

print(thislist)

['apple', 'banana', 'kiwi', 'cherry']


b. Create a list containing days of the week (starting with Sunday). Write a statement that indexes this list given an integer from 1 to 7 (defined as a variable "dayNum"), and prints out that day of the week. Note that if dayNum=1, your statement should print out Sunday - you will have to deal with the zero-indexing issue of Python!

In [40]:
days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

def WhatDay(dayNum, days_list):
    dayZeroIndex = dayNum - 1
    return (days_list[dayZeroIndex])

print(WhatDay(3, days))

Tuesday


### 6. Array assignment: Create a 3x3 array, and print out only the middle column.

In [47]:
array = np.arange(2, 11).reshape(3,3)
print(array)
print("Middle column is:")
print(array[ :,1])

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Middle column is:
[3 6 9]


### 7. Conditionals assignment:
Create a 2x2 numpy array, then compare the [0,0] and [1,1] elements of the array, and give a message about which is larger.

In [64]:
array = np.random.randint(100, size=(2,2))
print(array)

if array[0, 0] > array[1, 1]:
    print(f'[0,0] is larger with a value of {array[0,0]}')
elif array[0, 0] == array[1, 1]:
    print(f'Both entries have the same value of {array[0,0]}')
else:
    print(f'[1,1] is larger with a value of {array[1,1]}')


[[98 42]
 [85  9]]
[0,0] is larger with a value of 98


### 8. Loops assignment:
a. Create a nested for loop (two for loops inside each other) that populate the values of a 5x5 numpy array with the product of the two array index values. E.g:

    myarray[i,j] = i*j
    
Hint: we will first need to create a blank array of size 5x5. To do this, we use the following syntax:

    myarray=np.zeros((5,5))

In [71]:
array = np.zeros((5,5))

for row in range(5):
    for column in range(5):
        val = row * column
        array[row, column] = val

print(array)
        

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  4.  8. 12. 16.]]


b. Use a while loop to keep rolling a dice, and only stop when you roll a 6. To roll a dice from 1 to 6 in python, we can use:

    a = np.random.randint(1,7)

**Warning**: When trying out while loops, user beware! If you cause a bug that makes it run forever, use the square "stop" button at the top of the page. Occasionally it may crash your jupyter page.

**Note**: It's a good idea to use more informative variable names. Instead of calling your dice roll "a", give it a more informative name. This is a good habit to get into early on!

In [75]:
roll = 0

while roll != 6:
    print("Rolling!")
    roll = np.random.randint(1, 7)
    print(f'Rolled a {roll}')

Rolling!
Rolled a 3
Rolling!
Rolled a 3
Rolling!
Rolled a 2
Rolling!
Rolled a 4
Rolling!
Rolled a 4
Rolling!
Rolled a 1
Rolling!
Rolled a 6


### 9. Functions assignment: 
With all you've learned so far, you are now able to write some more or less fully-fledged programs! Here are a few exercises to practice your function mastery. For each one, give the function a sensible name, and test it with a few different inputs to make sure it works as you expect. 

a. Write a function that accepts 2 inputs: a string, and a number. The function should use a loop to print out the input string the specified number of times. Then call the function, using your name and favorite number as the input

In [76]:
def multi_print(string, times):
    for repeating in range(times):
        print(string)

multi_print("This is a test!", 7)

This is a test!
This is a test!
This is a test!
This is a test!
This is a test!
This is a test!
This is a test!


b. Convert your answer to question 1 above into a function called "deg2rad" that will convert any number input in degrees to radians


In [ ]:
import numpy as np

def deg2rad(degrees):
    radians=np.pi * degrees / 180
    return radians

def rad2deg(radians):
    degrees = 180/np.pi * radians
    return degrees

print(f'180 degrees is {deg2rad(180)} radians')
print(f'{np.pi} radians is {rad2deg(np.pi)} degrees')

c. Write a function that will convert geographic coordinates in degree (D), minute (M), second (S) to decimal degrees format (DMS to DD.DDDD)
    
      Hint: 1 minute = 1/60 degree, 1 second = 1/3600  degree

In [77]:
def DMS_to_DD(D, M, S):
    DD = D + ((1/60) * M) + ((1/3600) * S)
    return DD

print(DMS_to_DD(150, 35, 45))

150.59583333333333


d. (Complicated!) Write a function that will input year, month, day and output day of year (the so-called "Julian date")

   Tricky: beware of leap years, which are any years that can be exactly divided by 4, but not by 100 - i.e. 2004 is a leap year but 2000 is not.
   
   Hint: Python has a 'modulo' division symbol (%) that gives the remainder of division; this can tell you if a number is exactly divisible: for example, try 2015 % 4, and 2016 % 4
   

In [107]:
def julian_date(year, month, day):
    calendar_dict = {
        "January": [1, 31],
        "February": [2, 28],
        "March": [3, 31],
        "April": [4, 30],
        "May": [5, 31],
        "June": [6, 30],
        "July": [7, 31],
        "August": [8, 31],
        "September": [9, 30],
        "October": [10, 31],
        "November": [11, 30],
        "December": [12, 31]
    }

    if  year % 4 == 0: # Sets February's length to 29 during leap years
        calendar_dict["February"][1] = 29

    if month not in calendar_dict: # Several checks to see if day/month actually exists
        print('Invalid month')
        return
    if day > calendar_dict[month][1]:
        print('Invalid day')
        return
    elif day <= 0:
        print('Invalid day')
        return
    
    sum = 0
    max_month = calendar_dict[month][0] - 1 # We only want to add all the days from predecessing months
    
    for cur_month in calendar_dict: # Adds the length of previous months to our sum
        if calendar_dict[cur_month][0] <= max_month:
            sum += calendar_dict[cur_month][1]

    sum += day # Adds the number of days in this month

    return sum # Returns the day instead of printing for flexibility

print(f'Julian Date is {julian_date(2000, "November", 29)}')

Julian Date is 334


e. Optional: Re-do problem d, but using the built-in python module 'datetime'. Use google to find the manual for the datetime module. You may find the code is much shorter!

In [110]:
# ObsPy has a built in Julian day function that I find to be even easier than Python's date time

from obspy.core import UTCDateTime

test_time = UTCDateTime("2000-11-29")
print(test_time.julday)

334


### 10. Optional Assignment: modules

Make a module that contains a function that computes distance on a sphere by implementing one of the distance algorithms from https://en.wikipedia.org/wiki/Great-circle_distance.

Then import the module here, and compute the distance between Albuquerque (Lon, Lat: -106.62, 35.08) and your dream vacation destination.


In [47]:
import numpy as np

def Great_Circle(Loc1_Lon,Loc1_Lat,Loc2_Lon,Loc2_Lat,radius=6371.009, sigfigs=3):
    """
    Args:
    Loc1_Lon: Longitude of the first location
    Loc1_Lat: Latitude of the first location

    Loc2_Lon: Longitude of the first location
    Loc2_Lat: Latitude of the first location

    radius: Radius of Earth, defaults to 6371.009 kilometers because it provides the average smallest error
    sigfigs: Place to round to, set to false if no rounding desired.
    
    Returns:
    dist: Distance, in kilometers, between the two locations
    """

    # Making various checkpoints in the function for legibility and bug finding
    Loc1_Lon = np.deg2rad(Loc1_Lon)
    Loc1_Lat = np.deg2rad(Loc1_Lat)
    Loc2_Lon = np.deg2rad(Loc2_Lon)
    Loc2_Lat = np.deg2rad(Loc2_Lat)

    deltaLon = np.abs(Loc2_Lon - Loc1_Lon)
    check1 = (np.cos(Loc2_Lat) * np.sin(deltaLon))**2
    check2 = ((np.cos(Loc1_Lat) * np.sin(Loc2_Lat)) - (np.sin(Loc1_Lat) * np.cos(Loc2_Lat) * np.cos(deltaLon)))**2
    check3 = (np.sin(Loc1_Lat) * np.sin(Loc2_Lat)) + (np.cos(Loc1_Lat) * np.cos(Loc2_Lat) * np.cos(deltaLon))

    # Final arc length calculation
    deltaArc = np.arctan((np.sqrt(check1 + check2))/(check3))

    # Converts arc length to distance in km depending on if/how sigfigs is defined
    
    if isinstance(sigfigs, bool) == True:
        dist = deltaArc * radius
    elif isinstance(sigfigs, bool) == False:
        print(f"Calculating dist using sigfigs = {sigfigs}")
        dist = np.around((deltaArc * radius), sigfigs)
    return dist

print(f'Distance between these points is: {Great_Circle(-106.62, 35.08, -100, 30)} kilometers')

Calculating dist using sigfigs = 3
Distance between these points is: 838.738 kilometers


### 11. Optional Assignment: programming challenges!
Try a programming challenge from 
https://www.codecademy.com/resources/blog/python-code-challenges-for-beginners/, or https://pythonprinciples.com/challenges/.